### ISSUE TITLE
求助：Alias ('kkt',) not found. Try to match patterns

### ISSUE THREAD

**Issue by Robin-sys** [opq-osc/opqqq-plugin#16]
<img width="560" alt="2CFD772F67FAB8CEF07B272CD2D8C3F7" src="https://user-images.githubusercontent.com/58930956/119587191-be7be480-be00-11eb-9394-3fcda2850305.png">
在使用Pixiv看图的插件。
这个问题我该怎么着手去找呢？我可以收到收集失败的信息，但是也就这样了...

**Comment by xiyaowong** [comment]
> <img alt="2CFD772F67FAB8CEF07B272CD2D8C3F7" width="560" src="https://user-images.githubusercontent.com/58930956/119587191-be7be480-be00-11eb-9394-3fcda2850305.png">
> 
> 在使用Pixiv看图的插件。 这个问题我该怎么着手去找呢？我可以收到收集失败的信息，但是也就这样了...

这是啥。来错地方了吧

**Comment by fz6m** [comment]
已存档的项目将不再维护，同时不会对出现的问题提出解决方案，如需使用，请自行调试解决，感谢支持。

**Comment by fz6m** [comment]
已存档的项目将不再维护，同时不会对出现的问题提出解决方案，如需使用，请自行调试解决，感谢支持。

**Comment by Robin-sys** [comment]
谢谢您分享代码...
